LaptopSystemMyVersion/LaptopSystem.Web/Controllers/LaptopsController.cs
using LaptopSystem.Models;
using LaptopSystem.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Net.Http;

namespace LaptopSystem.Web.Controllers
{
    public class LaptopsController : BaseController
    {
        const int PageSize = 5;

        private IQueryable<LaptopViewModel> GetAllLaptops()
        {
            var laptops = this.Data.Laptops.Select(x => new LaptopViewModel()
            {
                Id = x.Id,
                ImageUrl = x.ImageUrl,
                Manufacturer = x.Manufacturer.Name,
                Model = x.Model,
                Price = x.Price
            }).OrderBy(x => x.Id);

            return laptops;
        }

        public ActionResult Details(int id)
        {
            var laptopDetailsViewModel = this.Data.Laptops
                .Where(x => x.Id == id)
                .Select(x => new LaptopDetailsViewModel()
                {
                    Id = x.Id,
                    AdditionalParts = x.AdditionalParts,
                    Comments = x.Comments.Select(y => new CommentViewModel()
                    {
                        AuthorUsername = y.Author.UserName,
                        Content = y.Content
                    }),
                    Description = x.Description,
                    HardDiskSize = x.HardDiskSize,
                    ImageUrl = x.ImageUrl,
                    Manufacturer = x.Manufacturer.Name,
                    Model = x.Model,
                    MonitorSize = x.MonitorSize,
                    Price = x.Price,
                    RamMemorySize = x.RamMemorySize,
                    Weight = x.Weight
                }).FirstOrDefault();

            return View(laptopDetailsViewModel);
        }

        public ActionResult List(int? id)
        {
            int pageNumber = id.GetValueOrDefault(1);
            var viewModel = 
                GetAllLaptops()
                .Skip((pageNumber - 1) * PageSize)
                .Take(PageSize);

            ViewBag.Pages = Math.Ceiling((double)GetAllLaptops().Count() / PageSize);

            return View(viewModel);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult PostComment(SubmitCommentModel commentModel)
        {
            if (ModelState.IsValid)
            {
                this.Data.Comments.Add(new Comment()
                {
                    AuthorId = this.User.Identity.GetUserId(),
                    Content = commentModel.Comment,
                    LaptopId = commentModel.LaptopId
                });

                this.Data.SaveChanges();

                var viewModel = new CommentViewModel()
                {
                    AuthorUsername = this.User.Identity.GetUserName(),
                    Content = commentModel.Comment
                };
                return PartialView("_CommentPartial", viewModel);
            }
            else
            {
                return new HttpStatusCodeResult
                    (System.Net.HttpStatusCode.BadRequest, 
                    ModelState.Values.First().ToString());
            }
        }
    }
}

LaptopSystemMyVersion/LaptopSystem.Web/Controllers/ManufacturersAdministrationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LaptopSystem.Models;
using LaptopSystem.Data;

namespace LaptopSystem.Web.Controllers
{
    //[Authorize(Roles="Admin")]
    public class ManufacturersAdministrationController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /ManufacturersAdministration/
        public ActionResult Index()
        {
            return View(db.Manufacturers.ToList());
        }

        // GET: /ManufacturersAdministration/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Manufacturer manufacturer = db.Manufacturers.Find(id);
            if (manufacturer == null)
            {
                return HttpNotFound();
            }
            return View(manufacturer);
        }

        // GET: /ManufacturersAdministration/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /ManufacturersAdministration/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Name")] Manufacturer manufacturer)
        {
            if(db.Manufacturers.Any(x => x.Name == manufacturer.Name))
            {
                ModelState.AddModelError("Name", "There is already a manufacturer with this name!");
            }
            if (ModelState.IsValid)
            {
                db.Manufacturers.Add(manufacturer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(manufacturer);
        }

        // GET: /ManufacturersAdministration/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Manufacturer manufacturer = db.Manufacturers.Find(id);
            if (manufacturer == null)
            {
                return HttpNotFound();
            }
            return View(manufacturer);
        }

        // POST: /ManufacturersAdministration/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Name")] Manufacturer manufacturer)
        {
            if (db.Manufacturers.Any(x => x.Name == manufacturer.Name))
            {
                ModelState.AddModelError("Name", "There is already a manufacturer with this name!");
            }
            if (ModelState.IsValid)
            {
                db.Entry(manufacturer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(manufacturer);
        }

        // GET: /ManufacturersAdministration/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Manufacturer manufacturer = db.Manufacturers.Find(id);
            if (manufacturer == null)
            {
                return HttpNotFound();
            }
            return View(manufacturer);
        }

        // POST: /ManufacturersAdministration/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Manufacturer manufacturer = db.Manufacturers.Find(id);
            db.Manufacturers.Remove(manufacturer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LaptopSystemMyVersion/LaptopSystem.Web/Views/Shared/_CommentPartial.cshtml
@model LaptopSystem.Web.Models.CommentViewModel

<div>
    <div>
        CommentedBy: <em>@Model.AuthorUsername</em>
    </div>
    <div>
        @Model.Content
    </div>
</div>

LaptopSystemMyVersion/LaptopSystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Laptop System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Laptops List", "List", "Laptops")</li>
                    <li>@Html.ActionLink("Manufacturer admin", "Index", "ManufacturersAdministration")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <h1>LaptopSystem</h1>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Iliyan Hristov</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>